

# This is a basic workflow to help you get started with Actions

name: cron vet

# Controls when the workflow will run
on:
  schedule: # “End of the day”
    - cron: "0 4 * * *"
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: curl vet
      run: |
        curl -X GET "https://vetlibrary.tufts.edu"
